[package]
name = "dotfile_templater"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
thiserror = "2.0.12"
toml = "0.8.23"
