[package]
name = "dotfile_templater"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
toml = "0.8.23"
